/*The section builders purpose is to take a teamstructure, a team, and a 
quadrant and this is used to generate GBGroups with units that are have 
coordinates (quadrants are used by team structure to populate locations using 
the UnitPlacement Class), model strings (model numbers are added during when the 
load step occurs since whole folders are currently loaded before their size is 
known).  This class is used for initial creation of GBGroups and will select 
subteams for non-war maps. The strings in each of the team maps are used to 
populate the model strings. Model strings are the file path to where models can 
be loaded from, later a model number is added that is used to select the array 
position when the models accessed at runtime. Once GBGroups are made (either 
from loading or generated by the SectionBuilder class) they are used to create 
UnitGroups which are the runtime equivalent.*/
public class SectionBuilder{

    private var teamBuilders: Hashtable;//Section builders for each team (civilian, zombies, horde etc)
    private static var secBld:SectionBuilder;

/*"EternianRepublicTeams/", "InitiativeTeams/", "NightHordeTeams/", 
"PantheonTeams/", "SentaiClanTeams/", "ShadowEmpireTeams/", 
"UnitedLeagueTeams/", "UtromSithAllianceTeams/"*/
    public function SectionBuilder(){
        teamBuilders= new Hashtable();
        teamBuilders["civilians"]           = SectionBuilderCivilians.getSecBld();
        teamBuilders["zombies"]             = SectionBuilderZombies.getSecBld();
        teamBuilders["eternian_republic"]   = SectionBuilderEternianRepublic.getSecBld();
        teamBuilders["initiative"]          = SectionBuilderInitiative.getSecBld();
        teamBuilders["night_horde"]         = SectionBuilderNightHorde.getSecBld();
        teamBuilders["pantheon"]            = SectionBuilderPantheon.getSecBld();
        teamBuilders["sentai_clan"]         = SectionBuilderSentaiClan.getSecBld();
        teamBuilders["shadow_empire"]       = SectionBuilderShadowEmpire.getSecBld();
        teamBuilders["united_league"]       = SectionBuilderUnitedLeague.getSecBld();
        teamBuilders["utrom_sith_alliance"] = SectionBuilderUtromSithAlliance.getSecBld();
        teamBuilders["workers"]             = SectionBuilderWorkers.getSecBld();
    }

    /*Takes a team Structure, a team and a quadrant and returns a GBGroup.  
    First it creates a group, populates it with GBUnits, then updates their 
    locations (places them) of these GBUnits*/
	public function generateAndPlace(ts:TeamStructure, team:String, quadrant:int, groupID:int){
            //Teams can will randomly select from there list of subteams if they have them
            //Future work may include missions preselecting subteams.
        return teamBuilders[team].generateAndPlace(ts, quadrant, groupID);
	}

	public function generateAndPlace(ts:TeamStructure, quadrant:int, groupID:int){
		//abstract class
	}

	public static function getSecBld(){
        if(secBld==null){
        	secBld= new SectionBuilder();
        }
        return secBld;
	}
}
